stages:
  - build
  - test

# Global cache configuration
# Using a fixed key ensures 'test_job' can use the files 'build_job' downloaded
cache:
  key: maven-cache-v1
  paths:
    - .m2/repository

# Configuration shared by both jobs
.maven_setup: &maven_setup
  image: eclipse-temurin:17-jdk-alpine
  before_script:
    - chmod +x mvnw

build_job:
  <<: *maven_setup
  stage: build
  script:
    - >
      ./mvnw compile 
      -Dhttps.protocols=TLSv1.2 
      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository 
      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN 
      -Dorg.slf4j.simpleLogger.showDateTime=true 
      -Djava.awt.headless=true 
      --batch-mode --errors --fail-at-end --show-version 
      -DinstallAtEnd=true -DdeployAtEnd=true

test_job:
  <<: *maven_setup
  stage: test
  script:
    - >
      ./mvnw test 
      -Dhttps.protocols=TLSv1.2 
      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository 
      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN 
      -Dorg.slf4j.simpleLogger.showDateTime=true 
      -Djava.awt.headless=true 
      --batch-mode --errors --fail-at-end --show-version 
      -DinstallAtEnd=true -DdeployAtEnd=true